java.lang.AssertionError: NoDenotation.owner
occurred in the presentation compiler.

action parameters:
uri: file:///D:/Git/FP/fpinscala/Chapter4/src/main/scala/fpinscala/datatypes/Validated.scala
text:
package fpinscala.datatypes

import Either.*

enum Validated[+E, +A]:
  case Valid(get: A)
  case Invalid(errors: List[E])

  def toEither: Either[List[E], A] = this match
    case Valid(a)    => Either.Right(a)
    case Invalid(es) => Either.Left(es)

  def map[B](f: A => B): Validated[E, B] = this match
    case Valid(a)    => Valid(f(a))
    case Invalid(es) => Invalid(es)

  def map2[EE >: E, B, C](b: Validated[EE, B])(
      f: (A, B) => C
  ): Validated[EE, C] = (this, b) match
    case (Valid(aa), Valid(bb))       => Valid(f(aa, bb))
    case (Invalid(es), Valid(_))      => Invalid(es)
    case (Valid(_), Invalid(es))      => Invalid(es)
    case (Invalid(es1), Invalid(es2)) => Invalid(es1 ++ es2)

enum Validated[+E, +A]:
  case Valid(get: A)
  case Invalid(errors: List[E])

  // Exercise 4.8
  // In this implementation, map2 is only able to report one error, even if both
  // the name and the age are invalid. What would you need to change in order to
  // report both errors? Would you change map2 or the signature of mkPerson? Or
  // could you create a new data type that captures this requirement better than
  // Either does, with some additional structure? How would orElse, traverse, and
  // sequence behave differently for that data type?
  def map[B](f: A => B): Validated[E, B] = ???

  def map2[E, B, C](b: Validated[E, B])(
      f: (A, B) => C
  ): Validated[E, C] = ???

  def flatMap[E, B](f: A => Validated[E, B]): Validated[E, B] = ???

  def orElse[E, A](f: => Validated[E, A]): Validated[E, A] = ???

  def toEither: Either[List[E], A] = this match
    case Valid(a)    => Right(a)
    case Invalid(es) => Left(es)

object Validated:
  def fromEither[E, A](e: Either[List[E], A]): Validated[E, A] =
    e match
      case Either.Right(a) => Valid(a)
      case Either.Left(es) => Invalid(es)

  def traverse[E, A, B](
      as: List[A],
      f: A => Validated[E, B]
  ): Validated[E, List[B]] = ???

  def sequence[E, A](vs: List[Validated[E, A]]): Validated[E, List[A]] = ???



error stacktrace:
dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2576)
	dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:190)
	dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1660)
	dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1660)
	dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1624)
	dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1538)
	dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1661)
	dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:178)
	dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse$$anonfun$1(ExtractSemanticDB.scala:142)
	scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	scala.collection.immutable.List.foreach(List.scala:333)
	dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:142)
	scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:38)
	scala.meta.internal.pc.ScalaPresentationCompiler.semanticdbTextDocument$$anonfun$1(ScalaPresentationCompiler.scala:174)
